### ISSUE TITLE
response does not match example

### ISSUE THREAD

**Issue by nick-youngblut** [EBI-Metagenomics/emgapi#222]
This example in the [EMG-docs](https://emg-docs.readthedocs.io/en/latest/api.html)

```
curl -X GET "https://www.ebi.ac.uk/metagenomics/api/latest/studies/ERP005831?include=samples&fields[studies]=accession,study_name,biomes,samples&fields[samples]=accession,longitude,latitude,biome"
```

returns the following:

```
{"data":
  {"type":"studies", "id":"MGYS00000389", "attributes":
    {"accession":"MGYS00000389","study-name":
      "Stable isotope probing/metagenomics of terrestrial dimethylsulfide degrading microorganisms"},
   "relationships":
     {"samples":
       {"links":
         {"related":
           "https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00000389/samples"}},
    "biomes":
      {"links":
        {"related":
          "https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00000389/biomes"},
    "data":
      [{"type":"biomes","id":"root:Environmental:Aquatic:Freshwater:Lentic:Sediment","links": 
       {"self":"https://www.ebi.ac.uk/metagenomics/api/v1/biomes/root:Environmental:Aquatic:Freshwater:Lentic:Sediment"}}, 
       {"type":"biomes","id":"root:Environmental:Terrestrial:Soil:Loam:Agricultural","links": 
{"self":"https://www.ebi.ac.uk/metagenomics/api/v1/biomes/root:Environmental:Terrestrial:Soil:Loam:Agricultural"}}
       ]}},
    "links":
      {"self":
         "https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00000389"}}}
```

instead of the all of the info listed in the response in the docs (eg., `included: "accession": "ERS456668" &  "accession": "ERS456669"`)

OS: `Ubuntu 18.04.5 LTS`

**Comment by SandyRogers** [comment]
Thanks for raising this.

I've moved the issue from the Docs repo to [the EMG API repo](https://github.com/EBI-Metagenomics/emgapi/issues/222) because it seems like the `?include=...` API parameters should still be supported. 

The issue is how to support having the same related resource (`samples`) present as a linked resource list in `relationships: [...]` and in `included: [...]`. I'll investigate how to get this working again.

You can obtain the study's samples and it's attributes by requesting the related link (`curl -X GET "https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00000389/samples"`)
